import esri = __esri;
import Widget from '@arcgis/core/widgets/Widget';
import Sketch from '@arcgis/core/widgets/Sketch';
export default class DrawViewModel extends Widget {
    view: esri.MapView | esri.SceneView;
    label: string;
    fill: string;
    outline: string;
    fillOpacity: number;
    outlineOpacity: number;
    outlineWidth: number;
    geometryType: string;
    pointFillEnabled: boolean;
    polygonFillEnabled: boolean;
    sketch: Sketch;
    constructor(params?: any);
    sketchWidgetCreated: () => void;
    pointFillCreated: (picker: Element) => void;
    polygonFillCreated: (picker: Element) => void;
    pointOutlineCreated: (picker: Element) => void;
    lineOutlineCreated: (picker: Element) => void;
    polygonOutlineCreated: (picker: Element) => void;
    pointFillOpacityCreated: (slider: Element) => void;
    polygonFillOpacityCreated: (slider: Element) => void;
    pointOutlineOpacityCreated: (slider: Element) => void;
    lineOutlineOpacityCreated: (slider: Element) => void;
    polygonOutlineOpacityCreated: (slider: Element) => void;
    pointOutlineWidthCreated: (slider: Element) => void;
    lineOutlineWidthCreated: (slider: Element) => void;
    polygonOutlineWidthCreated: (slider: Element) => void;
    pointSizeCreated: (slider: Element) => void;
    pointFillEnabledCreated: (element: Element) => void;
    polygonFillEnabledCreated: (element: Element) => void;
    init(view: esri.MapView | esri.SceneView): void;
}
